path:
  ckpt_path: "./output_ver40/ckpt/JTES"
  log_path: "./output_ver40/log/JTES"
  result_path: "./output_ver40/result/JTES/500000/koruri"
  pre_model_path: "./output_ver40/ckpt/JTES"
optimizer:
  batch_size: 6
  betas: [0.9, 0.98]
  eps: 0.000000001
  weight_decay: 0.0
  grad_clip_thresh: 1.0
  grad_acc_step: 1
  warm_up_step: 4000
  anneal_steps: [300000, 400000, 500000]
  anneal_rate: 0.3
step:
  total_step: 900000
  log_step: 100
  synth_step: 1000
  val_step: 1000
  save_step: 10000
dataparallel: False