dataset: "JSUT"

path:
  corpus_path: "/home/nakata/jsut_ver1.1_original"
  lexicon_path: ""
  raw_path: "./raw_data/JSUT"
  preprocessed_path: "./preprocessed_data/JSUT"

preprocessing:
  val_size: 512
  test_size: 100
  text:
    text_cleaners: ["english_cleaners"]
    language: "ja"
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
    image: True
  energy:
    feature: "phoneme_level" # support 'phoneme_level' or 'frame_level'
    normalization: True
    image: True
  accent:
    use_accent: False
  image:
    use_image: False
    width: 30
    height: 30
    font_size: 15
    slice_width: 30
    slice_height: 30
    stride: 30
  input:
    kana: True