dataset: "LJSpeech"

path:
  raw_path: "./raw_data/LJSpeech"
  preprocessed_path: "./preprocessed_data/LJSpeech"

preprocessing:
  val_size: 512
  test_size: 100
  audio:
    sampling_rate: 22050
    max_wav_value: 32768.0
  stft:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
  mel:
    n_mel_channels: 80
    mel_fmin: 0
    mel_fmax: 8000 # please set to 8000 for HiFi-GAN vocoder, set to null for MelGAN vocoder
  pitch:
    feature: "character_level" # support 'character_level' or 'frame_level'
    normalization: True
  energy:
    feature: "character_level" # support 'character_level' or 'frame_level'
    normalization: True
  image:
    width: 30
    height: 30
    font_size: 20
    slice_width: 150
    slice_height: 30
    stride: 30
    font_path: "./font_ttf/ipag.ttf"